# Generated by Django 5.2.4 on 2025-08-20 09:51

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compound',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='compound',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='compound',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='formula',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='compound',
            name='molecular_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='compound',
            name='smiles',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='compound',
            index=models.Index(fields=['name'], name='compounds_c_name_42df29_idx'),
        ),
        migrations.AddIndex(
            model_name='compound',
            index=models.Index(fields=['formula'], name='compounds_c_formula_3a0e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='compound',
            index=models.Index(fields=['smiles'], name='compounds_c_smiles_73ebf1_idx'),
        ),
        migrations.AddIndex(
            model_name='compound',
            index=models.Index(fields=['is_public'], name='compounds_c_is_publ_6e4d13_idx'),
        ),
        migrations.AddIndex(
            model_name='compound',
            index=models.Index(fields=['owner', 'is_public'], name='compounds_c_owner_i_86fcab_idx'),
        ),
    ]
